set shell := ["bash", "-cu"]

port := `python3 -c "import yaml; print(yaml.safe_load(open('config.yaml'))['server']['port'])"`

default:
    just run

# run the server
run:
    ./setup_venv.sh
    just grpc-generate
    source ./venv/bin/activate && \
    python3 pyvisa_grpc_server.py

# connect grpcui to server for testing
grpcui:
    grpcui -plaintext localhost:{{port}}

# update stubs
grpc-generate:
    source ./venv/bin/activate && \
    python3 -m grpc_tools.protoc \
        -I../protos \
        --python_out=. \
        --grpc_python_out=. \
        ../protos/pyvisa_grpc.proto

# generate ssl certs for encrypted gRPC comms
ssl-generate:
    mkdir certs && \
    openssl req -x509 -newkey rsa:4096 -keyout certs/server.key -out certs/server.pem -days 365 -nodes -subj "/CN=localhost"
