# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pyvisa_grpc.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'pyvisa_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11pyvisa_grpc.proto\x12\x0bpyvisa_grpc\",\n\x13OpenResourceRequest\x12\x15\n\rresource_name\x18\x01 \x01(\t\"\'\n\x14OpenResourceResponse\x12\x0f\n\x07session\x18\x01 \x01(\t\"\'\n\x14\x43loseResourceRequest\x12\x0f\n\x07session\x18\x01 \x01(\t\"(\n\x15\x43loseResourceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0bReadRequest\x12\x0f\n\x07session\x18\x01 \x01(\t\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"-\n\x0cWriteRequest\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\rErrorResponse\x12\x15\n\rerror_message\x18\x01 \x01(\t\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb9\x02\n\rPyVISAService\x12S\n\x0cOpenResource\x12 .pyvisa_grpc.OpenResourceRequest\x1a!.pyvisa_grpc.OpenResourceResponse\x12V\n\rCloseResource\x12!.pyvisa_grpc.CloseResourceRequest\x1a\".pyvisa_grpc.CloseResourceResponse\x12;\n\x04Read\x12\x18.pyvisa_grpc.ReadRequest\x1a\x19.pyvisa_grpc.ReadResponse\x12>\n\x05Write\x12\x19.pyvisa_grpc.WriteRequest\x1a\x1a.pyvisa_grpc.WriteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pyvisa_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENRESOURCEREQUEST']._serialized_start=34
  _globals['_OPENRESOURCEREQUEST']._serialized_end=78
  _globals['_OPENRESOURCERESPONSE']._serialized_start=80
  _globals['_OPENRESOURCERESPONSE']._serialized_end=119
  _globals['_CLOSERESOURCEREQUEST']._serialized_start=121
  _globals['_CLOSERESOURCEREQUEST']._serialized_end=160
  _globals['_CLOSERESOURCERESPONSE']._serialized_start=162
  _globals['_CLOSERESOURCERESPONSE']._serialized_end=202
  _globals['_READREQUEST']._serialized_start=204
  _globals['_READREQUEST']._serialized_end=234
  _globals['_READRESPONSE']._serialized_start=236
  _globals['_READRESPONSE']._serialized_end=264
  _globals['_WRITEREQUEST']._serialized_start=266
  _globals['_WRITEREQUEST']._serialized_end=311
  _globals['_WRITERESPONSE']._serialized_start=313
  _globals['_WRITERESPONSE']._serialized_end=345
  _globals['_ERRORRESPONSE']._serialized_start=347
  _globals['_ERRORRESPONSE']._serialized_end=385
  _globals['_STATUSRESPONSE']._serialized_start=387
  _globals['_STATUSRESPONSE']._serialized_end=437
  _globals['_PYVISASERVICE']._serialized_start=440
  _globals['_PYVISASERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
