# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pyvisa_grpc_pb2 as pyvisa__grpc__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pyvisa_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PyVISAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenResource = channel.unary_unary(
                '/pyvisa_grpc.PyVISAService/OpenResource',
                request_serializer=pyvisa__grpc__pb2.OpenResourceRequest.SerializeToString,
                response_deserializer=pyvisa__grpc__pb2.OpenResourceResponse.FromString,
                _registered_method=True)
        self.CloseResource = channel.unary_unary(
                '/pyvisa_grpc.PyVISAService/CloseResource',
                request_serializer=pyvisa__grpc__pb2.CloseResourceRequest.SerializeToString,
                response_deserializer=pyvisa__grpc__pb2.CloseResourceResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/pyvisa_grpc.PyVISAService/Read',
                request_serializer=pyvisa__grpc__pb2.ReadRequest.SerializeToString,
                response_deserializer=pyvisa__grpc__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/pyvisa_grpc.PyVISAService/Write',
                request_serializer=pyvisa__grpc__pb2.WriteRequest.SerializeToString,
                response_deserializer=pyvisa__grpc__pb2.WriteResponse.FromString,
                _registered_method=True)


class PyVISAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenResource(self, request, context):
        """Open a resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseResource(self, request, context):
        """Close a resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Read from a resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Write to a resource
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PyVISAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenResource': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenResource,
                    request_deserializer=pyvisa__grpc__pb2.OpenResourceRequest.FromString,
                    response_serializer=pyvisa__grpc__pb2.OpenResourceResponse.SerializeToString,
            ),
            'CloseResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseResource,
                    request_deserializer=pyvisa__grpc__pb2.CloseResourceRequest.FromString,
                    response_serializer=pyvisa__grpc__pb2.CloseResourceResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=pyvisa__grpc__pb2.ReadRequest.FromString,
                    response_serializer=pyvisa__grpc__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=pyvisa__grpc__pb2.WriteRequest.FromString,
                    response_serializer=pyvisa__grpc__pb2.WriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pyvisa_grpc.PyVISAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pyvisa_grpc.PyVISAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PyVISAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pyvisa_grpc.PyVISAService/OpenResource',
            pyvisa__grpc__pb2.OpenResourceRequest.SerializeToString,
            pyvisa__grpc__pb2.OpenResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pyvisa_grpc.PyVISAService/CloseResource',
            pyvisa__grpc__pb2.CloseResourceRequest.SerializeToString,
            pyvisa__grpc__pb2.CloseResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pyvisa_grpc.PyVISAService/Read',
            pyvisa__grpc__pb2.ReadRequest.SerializeToString,
            pyvisa__grpc__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pyvisa_grpc.PyVISAService/Write',
            pyvisa__grpc__pb2.WriteRequest.SerializeToString,
            pyvisa__grpc__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
